// The pre-scored challenge trees, typed. The JSON is generated by
// src/challenge/build.ts (see generate.test.ts) and loads only with the
// landing chunk and the Worker, never the entry chunk.
import type { ChallengeTree, ChallengeTrees } from './score'
import data from './trees.generated.json'

/** Bump when build.ts changes how options are priced or graded. */
export const CHALLENGE_GRADER = 'challenge.v1+range-balanced'

export const TREES = data as ChallengeTrees

export const treeFor = (id: string, ver?: number): ChallengeTree | undefined =>
  TREES.hands.find((h) => h.id === id && (ver === undefined || h.ver === ver))
